version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16.13
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@15.2.4
  build:
    commands:
      - echo "Building Angular project..."
      - npm run build
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/angular-app/ s3://angular-app-codebuild --delete